import { Resend } from 'resend';

export const config = {
    runtime: 'edge', // Use Edge Runtime for speed
};

const resend = new Resend(process.env.RESEND_API_KEY);

export default async function handler(req) {
    if (req.method !== 'POST') {
        return new Response(JSON.stringify({ error: 'Method not allowed' }), { status: 405, headers: { 'Content-Type': 'application/json' } });
    }

    try {
        const { email, report } = await req.json();

        if (!email || !report) {
            return new Response(JSON.stringify({ error: 'Missing email or report data' }), { status: 400, headers: { 'Content-Type': 'application/json' } });
        }

        // Basic HTML template for the email
        const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="background-color: #000; color: #fff; padding: 20px; text-transform: uppercase;">Deep Dive Report: ${report.brand_name}</h1>
        
        <div style="padding: 20px; border: 4px solid #000; margin-top: 20px;">
          <h2 style="border-bottom: 2px solid #000; padding-bottom: 10px;">Executive Summary</h2>
          <ul>
            ${report.executive_summary.map(item => `<li style="margin-bottom: 10px;">${item}</li>`).join('')}
          </ul>

          <h2 style="border-bottom: 2px solid #000; padding-bottom: 10px; margin-top: 30px;">Overview</h2>
          <p><strong>Market:</strong> ${report.country || 'Global'}</p>
          <p><strong>Ticker:</strong> ${report.ticker || 'N/A'}</p>
          <p><strong>Target Persona:</strong> ${report.target_persona?.job_to_be_done || 'N/A'}</p>

          <h2 style="border-bottom: 2px solid #000; padding-bottom: 10px; margin-top: 30px;">Marketing 4Ps</h2>
          <p><strong>Product:</strong> ${report.marketing_4ps?.product}</p>
          <p><strong>Price:</strong> ${report.marketing_4ps?.price}</p>
          <p><strong>Place:</strong> ${report.marketing_4ps?.place}</p>
          <p><strong>Promotion:</strong> ${report.marketing_4ps?.promotion}</p>

          <h2 style="border-bottom: 2px solid #000; padding-bottom: 10px; margin-top: 30px;">Financials (Latest)</h2>
          <p><strong>Revenue:</strong> ${report.financials?.revenue_latest}</p>
          <p><strong>Market Cap:</strong> ${report.financials?.market_cap}</p>

          <div style="margin-top: 40px; text-align: center; color: #666; font-size: 12px;">
            <p>Generated by AimLow.ai • BETA Pro Analyst</p>
          </div>
        </div>
      </div>
    `;

        const data = await resend.emails.send({
            from: 'AimLow Analyst <analyst@aimlow.ai>', // User needs to configure a verified domain or use Resend's testing on boarding
            to: email, // Sending to the registered user
            subject: `Your Deep Dive Report: ${report.brand_name}`,
            html: htmlContent,
        });

        return new Response(JSON.stringify({ success: true, id: data.id }), { status: 200, headers: { 'Content-Type': 'application/json' } });

    } catch (error) {
        console.error('Email sending failed:', error);
        return new Response(JSON.stringify({ error: error.message || 'Failed to send email' }), { status: 500, headers: { 'Content-Type': 'application/json' } });
    }
}
